# Change these first
owner: generator-labs
repo: status

sites:
  - name: RBLTracker Website
    url: https://rbltracker.com
  - name: RBLTracker API
    url: https://api.rbltracker.com/3.0/ping

status-website:
  cname: status.generatorlabs.com
  baseUrl: /
  logoUrl: https://status.generatorlabs.com/rbl-logo.svg
  name: RBLTracker System Status
  themeUrl: https://status.generatorlabs.com/custom-theme.css
  favicon: https://status.generatorlabs.com/favicon.ico
  faviconSvg: https://status.generatorlabs.com/favicon.svg

i18n:
  footer: 
