owner: generator-labs
repo: status

sites:
  - name: RBL Monitoring
    url: https://api.rbltracker.com/1.0/rbl
    icon: https://status.generatorlabs.com/favicon.ico
  - name: REST API
    url: https://api.rbltracker.com/1.0/ping
    icon: https://status.generatorlabs.com/favicon.ico
  - name: rbltracker.com Website
    url: https://rbltracker.com
    icon: https://status.generatorlabs.com/favicon.ico

status-website:
  cname: status.generatorlabs.com
  logoUrl: https://status.generatorlabs.com/rbl-logo.svg
  name: RBLTracker System Status
  themeUrl: https://status.generatorlabs.com/custom-theme.css
  favicon: https://status.generatorlabs.com/favicon.ico
  faviconSvg: https://status.generatorlabs.com/favicon.svg

i18n:
  footer: Copyright © 2025 Generator Labs, Inc.
